# Global, no hard-coding. Change dirs/targets here only.
project_name: "AIX-HACKATHON"

# Data locations (all relative to repo root unless absolute)
data_dir: "./data"
interim_dir: "./data/interim"
processed_dir: "./data/processed"
raw_dir: "./data/raw"

# Regulator namespaces. Add more without touching code.
regulators:
  - id: "qcb"
    name: "Qatar Central Bank"
    rulepack: "./config/regulators/qcb.yaml"
  - id: "qfc"
    name: "Qatar Financial Centre"
    rulepack: "./config/regulators/qfc.yaml"

# Defaults used by the chunker later
chunking:
  target_tokens: 800
  overlap_tokens: 120
